name: Build LaTeX Document

on:
  push:
    branches:
      - main

# Berechtigungen nur für diesen Workflow definieren
permissions:
  contents: write  # Schreib- und Lesezugriff auf Code/Dateien im Repository

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex

      - name: Commit and Push PDF to Root
        run: |
          mv main.pdf Bauphysik_Formelsammlung.pdf
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Bauphysik_Formelsammlung.pdf
          git commit -m "auto: Bauphysik_Formelsammlung.pdf aktualisiert [skip ci]" || echo "Keine Änderungen vorhanden"
          git push
